spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: CRUD

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    cache: false

  datasource:
    url: jdbc:mysql://localhost:3306/crud_db?serverTimezone=Asia/Seoul
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        format_sql: true

  devtools:
    restart:
      exclude: static/**,public/**,data/**

jwt:
  secret: your-secret-key
  access-expiration: 3600000
  refresh-expiration: 604800000
